/*
        redkea library for Arduino
        Copyright 2017 redkea

        This file is part of the redkea library for Arduino.

    The redkea library for Arduino is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The redkea library for Arduino is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the redkea library for Arduino.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "RedkeaUserFunctions.h"

#define REDKEA_DEFINE_FUNCTION_RECEIVE(id) \
     void __attribute__((weak)) redkeaReceive ## id(RedkeaMessage::Args arg) { REDKEA_PRINTLN("Receive function not implmented"); }

#define REDKEA_DEFINE_FUNCTION_SEND(id) \
     void __attribute__((weak)) redkeaSend ## id(const char widgetID[UID_LENGTH]) { REDKEA_PRINTLN("Send function not implmented"); }

/*
* WRITE FUNCTIONS
**/

REDKEA_DEFINE_FUNCTION_RECEIVE(0)
REDKEA_DEFINE_FUNCTION_RECEIVE(1)
REDKEA_DEFINE_FUNCTION_RECEIVE(2)
REDKEA_DEFINE_FUNCTION_RECEIVE(3)
REDKEA_DEFINE_FUNCTION_RECEIVE(4)
REDKEA_DEFINE_FUNCTION_RECEIVE(5)
REDKEA_DEFINE_FUNCTION_RECEIVE(6)
REDKEA_DEFINE_FUNCTION_RECEIVE(7)
REDKEA_DEFINE_FUNCTION_RECEIVE(8)
REDKEA_DEFINE_FUNCTION_RECEIVE(9)

REDKEA_DEFINE_FUNCTION_RECEIVE(10)
REDKEA_DEFINE_FUNCTION_RECEIVE(11)
REDKEA_DEFINE_FUNCTION_RECEIVE(12)
REDKEA_DEFINE_FUNCTION_RECEIVE(13)
REDKEA_DEFINE_FUNCTION_RECEIVE(14)
REDKEA_DEFINE_FUNCTION_RECEIVE(15)
REDKEA_DEFINE_FUNCTION_RECEIVE(16)
REDKEA_DEFINE_FUNCTION_RECEIVE(17)
REDKEA_DEFINE_FUNCTION_RECEIVE(18)
REDKEA_DEFINE_FUNCTION_RECEIVE(19)

REDKEA_DEFINE_FUNCTION_RECEIVE(20)
REDKEA_DEFINE_FUNCTION_RECEIVE(21)
REDKEA_DEFINE_FUNCTION_RECEIVE(22)
REDKEA_DEFINE_FUNCTION_RECEIVE(23)
REDKEA_DEFINE_FUNCTION_RECEIVE(24)
REDKEA_DEFINE_FUNCTION_RECEIVE(25)
REDKEA_DEFINE_FUNCTION_RECEIVE(26)
REDKEA_DEFINE_FUNCTION_RECEIVE(27)
REDKEA_DEFINE_FUNCTION_RECEIVE(28)
REDKEA_DEFINE_FUNCTION_RECEIVE(29)

REDKEA_DEFINE_FUNCTION_RECEIVE(30)
REDKEA_DEFINE_FUNCTION_RECEIVE(31)
REDKEA_DEFINE_FUNCTION_RECEIVE(32)
REDKEA_DEFINE_FUNCTION_RECEIVE(33)
REDKEA_DEFINE_FUNCTION_RECEIVE(34)
REDKEA_DEFINE_FUNCTION_RECEIVE(35)
REDKEA_DEFINE_FUNCTION_RECEIVE(36)
REDKEA_DEFINE_FUNCTION_RECEIVE(37)
REDKEA_DEFINE_FUNCTION_RECEIVE(38)
REDKEA_DEFINE_FUNCTION_RECEIVE(39)


/*
 * READ FUNCTIONS
 **/

REDKEA_DEFINE_FUNCTION_SEND(0)
REDKEA_DEFINE_FUNCTION_SEND(1)
REDKEA_DEFINE_FUNCTION_SEND(2)
REDKEA_DEFINE_FUNCTION_SEND(3)
REDKEA_DEFINE_FUNCTION_SEND(4)
REDKEA_DEFINE_FUNCTION_SEND(5)
REDKEA_DEFINE_FUNCTION_SEND(6)
REDKEA_DEFINE_FUNCTION_SEND(7)
REDKEA_DEFINE_FUNCTION_SEND(8)
REDKEA_DEFINE_FUNCTION_SEND(9)

REDKEA_DEFINE_FUNCTION_SEND(10)
REDKEA_DEFINE_FUNCTION_SEND(11)
REDKEA_DEFINE_FUNCTION_SEND(12)
REDKEA_DEFINE_FUNCTION_SEND(13)
REDKEA_DEFINE_FUNCTION_SEND(14)
REDKEA_DEFINE_FUNCTION_SEND(15)
REDKEA_DEFINE_FUNCTION_SEND(16)
REDKEA_DEFINE_FUNCTION_SEND(17)
REDKEA_DEFINE_FUNCTION_SEND(18)
REDKEA_DEFINE_FUNCTION_SEND(19)

REDKEA_DEFINE_FUNCTION_SEND(20)
REDKEA_DEFINE_FUNCTION_SEND(21)
REDKEA_DEFINE_FUNCTION_SEND(22)
REDKEA_DEFINE_FUNCTION_SEND(23)
REDKEA_DEFINE_FUNCTION_SEND(24)
REDKEA_DEFINE_FUNCTION_SEND(25)
REDKEA_DEFINE_FUNCTION_SEND(26)
REDKEA_DEFINE_FUNCTION_SEND(27)
REDKEA_DEFINE_FUNCTION_SEND(28)
REDKEA_DEFINE_FUNCTION_SEND(29)

REDKEA_DEFINE_FUNCTION_SEND(30)
REDKEA_DEFINE_FUNCTION_SEND(31)
REDKEA_DEFINE_FUNCTION_SEND(32)
REDKEA_DEFINE_FUNCTION_SEND(33)
REDKEA_DEFINE_FUNCTION_SEND(34)
REDKEA_DEFINE_FUNCTION_SEND(35)
REDKEA_DEFINE_FUNCTION_SEND(36)
REDKEA_DEFINE_FUNCTION_SEND(37)
REDKEA_DEFINE_FUNCTION_SEND(38)
REDKEA_DEFINE_FUNCTION_SEND(39)